// Editor
export const SET_ACTIVE_SECTION = "SET_ACTIVE_SECTION";
export const UPDATE_SECTIONS_LOCK_STATE = "UPDATE_SECTIONS_LOCK_STATE";

// Lifepath editor
export const SELECT_RACE = "SELECT_RACE";
export const SELECT_LIFEPATH_COUNT = "SELECT_LIFEPATH_COUNT";
export const ADD_LIFEPATH = "ADD_LIFEPATH";
export const REMOVE_LIFEPATH = "REMOVE_LIFEPATH"

// Stats editor
export const SELECT_STAT_BONUS = "SELECT_STAT_BONUS";
export const SELECT_STAT = "SELECT_STAT";

// Skills editor
export const ADVANCE_SKILL = "ADVANCE_SKILL";
export const OPEN_GENERAL_SKILL = "OPEN_GENERAL_SKILL";
export const REMOVE_GENERAL_SKILL = "REMOVE_GENERAL_SKILL";

// Traits editor
export const BUY_TRAIT = "BUY_TRAIT";
export const ADD_TRAIT = "ADD_TRAIT";
export const REMOVE_TRAIT = "REMOVE_TRAIT";

// Attributes editor
export const ANSWER_HEALTH_QUESTIONS = "ANSWER_HEALTH_QUESTIONS";
export const ANSWER_STEEL_QUESTIONS = "ANSWER_STEEL_QUESTIONS";