// TODO: format stats, skills and traits.

export default
    [
        {
            name: "Born Clansman",
            setting: "Clansman",
            time: 20,
            res: 10,
            stats: "",
            "General Points": 3,
            "Skill Points": 0,
            "Trait Points": 1,
            "Skill List": "",
            "Trait List": "",
            leads: "Guilder",
            restrictions: "",
        },
        {
            name: "Tender",
            setting: "Clansman",
            time: 20,
            res: 7,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Hills-wise,Crop-wise,Farming",
            "Trait List": "Cursing",
            leads: "Guilder,Host",
            restrictions: "",
        },
        {
            name: "Herder",
            setting: "Clansman",
            time: 15,
            res: 9,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Climbing,Fence Building,Flock-wise,Animal Husbandry",
            "Trait List": "Affinity for Sheep and Goats,Booming Voice",
            leads: "Guilder,Host",
            restrictions: "",
        },
        {
            name: "Tinkerer",
            setting: "Clansman",
            time: 35,
            res: 15,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Scavenging,Mending,Stuff-wise",
            "Trait List": "Tinkerer,Curious",
            leads: "Guilder,Outcast",
            restrictions: "",
        },
        {
            name: "Delver",
            setting: "Clansman",
            time: 20,
            res: 10,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Excavation,Gas Pocket-wise,Tunnel-wise",
            "Trait List": "Deep Sense",
            leads: "Host,Guilder",
            restrictions: "",
        },
        {
            name: "Miller",
            setting: "Clansman",
            time: 30,
            res: 30,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Grain-wise,Brewer,Mending,Miller,Grain Appraisal",
            "Trait List": "",
            leads: "Guilder,Host",
            restrictions: "",
        },
        {
            name: "Brewer",
            setting: "Clansman",
            time: 40,
            res: 40,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Beer-wise,Miller,Nogger,Beer Appraisal",
            "Trait List": "",
            leads: "Guilder,Host,Outcast",
            restrictions: "Miller; Longbeard; Seneschal; Captain; or Drunk",
        },
        {
            name: "Foreman",
            setting: "Clansman",
            time: 35,
            res: 25,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Engineering,Vein-wise,Ore-wise",
            "Trait List": "",
            leads: "Guilder,Host,Artificer",
            restrictions: "Delver; Artificer's Ardent or Engineer",
        },
        {
            name: "Husband/Wife",
            setting: "Clansman",
            time: 70,
            res: 18,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Soothing Platitudes,Haggling,Family-wise,Clan-wise",
            "Trait List": "Pragmatic Outlook,Dispute-Settler",
            leads: "Guilder,Host,Outcast",
            restrictions: "Husband/Wife cannot be the 2nd lifepath",
        },
        {
            name: "Longbeard",
            setting: "Clansman",
            time: 77,
            res: 30,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Host-wise,Guilder-wise,Ugly Truth,Coarse Persuasion",
            "Trait List": "Oathswearer,Folksy Wisdom",
            leads: "Host,Outcast",
            restrictions: "Foreman; Graybeard; Artificer; Trader; Seneschal; Adventurer; or Husband/Wife",
        },
        {
            name: "Born Guilder",
            setting: "Guilder",
            time: 21,
            res: 5,
            stats: "",
            "General Points": 4,
            "Skill Points": 0,
            "Trait Points": 1,
            "Skill List": "",
            "Trait List": "",
            leads: "Clansman",
            restrictions: "",
        },
        {
            name: "Wordbearer",
            setting: "Guilder",
            time: 15,
            res: 10,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Clan History,Oratory,Rumor-wise,Hold-wise",
            "Trait List": "Quick-Step,Iron Memory,Quirky",
            leads: "Clansman,Host",
            restrictions: "",
        },
        {
            name: "Hauler",
            setting: "Guilder",
            time: 10,
            res: 7,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Road-wise,Cargo-wise,Wagon-wise,Hauling",
            "Trait List": "Lifting Heavy Things",
            leads: "Clansman,Host",
            restrictions: "",
        },
        {
            name: "Carter",
            setting: "Guilder",
            time: 20,
            res: 10,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mule-wise,Mending,Driving,Animal Husbandry",
            "Trait List": "Iron Nose,Patient",
            leads: "Clansman,Outcast",
            restrictions: "",
        },
        {
            name: "Hawker",
            setting: "Guilder",
            time: 15,
            res: 15,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Spiel-wise,Haggling,Streetwise,Conspicuous,Inconspicuous",
            "Trait List": "",
            leads: "Clansman,Outcast,Host",
            restrictions: "",
        },
        {
            name: "Apprentice",
            setting: "Guilder",
            time: 15,
            res: 20,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Scutwork-wise,Carpentry,Tanner,Carving",
            "Trait List": "Seen Not Heard",
            leads: "Clansman,Artificer",
            restrictions: "",
        },
        {
            name: "Journeyman",
            setting: "Guilder",
            time: 25,
            res: 25,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Black-Metal Artifice,Mending,Cartwright,Reputation-wise,Haggling",
            "Trait List": "Hungry",
            leads: "Clansman,Artificer,Host",
            restrictions: "Apprentice or any Ardent lifepath",
        },
        {
            name: "Craftsman",
            setting: "Guilder",
            time: 45,
            res: 45,
            stats: "1M/P",
            "General Points": 1,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Artificer-wise,Shipwright,Appraisal",
            "Trait List": "",
            leads: "Clansman,Artificer",
            restrictions: "Journeyman; Artificer; Artillerist; or Engineer",
        },
        {
            name: "Trader",
            setting: "Guilder",
            time: 45,
            res: 70,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Persuasion,Haggling,Shrewd Appraisal,Stentorious Debate",
            "Trait List": "",
            leads: "Clansman,Outcast",
            restrictions: "Hawker; Journeyman; Adventurer; or Husband/Wife",
        },
        {
            name: "Born Artificer",
            setting: "Artificer",
            time: 20,
            res: 15,
            stats: "",
            "General Points": 3,
            "Skill Points": 2,
            "Trait Points": 1,
            "Skill List": "",
            "Trait List": "",
            leads: "Clansman",
            restrictions: "",
        },
        {
            name: "Ardent",
            setting: "Artificer",
            time: 21,
            res: 15,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Soot-wise,Soothing Platitudes,Firebuilding",
            "Trait List": "Hard Work,Humility",
            leads: "Clansman,Noble,Host,Guilder",
            restrictions: "",
        },
        {
            name: "Tyro Artificer",
            setting: "Artificer",
            time: 21,
            res: 20,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Dwarven Art-wise,Mending,Black-Metal Artifice",
            "Trait List": "Determined",
            leads: "Guilder,Host,Outcast",
            restrictions: "Artificer's Ardent or Journeyman",
        },
        {
            name: "Artificer Setting",
            setting: "Artificer",
            time: 30,
            res: 35,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Gem Artifice,White-Metal Artifice,Etching,Stone Artifice",
            "Trait List": "Stolid",
            leads: "Outcast,Host",
            restrictions: "Tyro Artificer or Craftsman",
        },
        {
            name: "Mask Bearer",
            setting: "Artificer",
            time: 55,
            res: 50,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "War Art,Fire and Steel-wise,Jargon",
            "Trait List": "",
            leads: "Outcast,Host,Noble",
            restrictions: "Artificer",
        },
        {
            name: "Master of Arches",
            setting: "Artificer",
            time: 75,
            res: 55,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 2,
            "Skill List": "Etiquette,Symbology,Hallmaster,Sculpture,Lithography",
            "Trait List": "Patient,Confident",
            leads: "Outcast,Host",
            restrictions: "Artificer",
        },
        {
            name: "Master of Forges",
            setting: "Artificer",
            time: 75,
            res: 75,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Maker's Mark-wise,Command,Engineering,Appraisal,Forge Artifice",
            "Trait List": "Estimation,Meticulous",
            leads: "Outcast,Host",
            restrictions: "Mask Bearer",
        },
        {
            name: "Master Engraver",
            setting: "Artificer",
            time: 100,
            res: 60,
            stats: "1M",
            "General Points": 2,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Mountain-wise,Stone-wise,Reason of Old Stone",
            "Trait List": "",
            leads: "Outcast,Host",
            restrictions: "Master of Arches",
        },
        {
            name: "Born Noble",
            setting: "Dwarven Noble",
            time: 21,
            res: 10,
            stats: "",
            "General Points": 4,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Dwarven Rune Script",
            "Trait List": "Dvergar",
            leads: "Guilder,Artificer",
            restrictions: "",
        },
        {
            name: "Abecedart",
            setting: "Dwarven Noble",
            time: 20,
            res: 10,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Obscure Text-wise,Etiquette,Chronology of Kings",
            "Trait List": "Know It All",
            leads: "Guilder,Artificer,Outcast",
            restrictions: "",
        },
        {
            name: "Ardent",
            setting: "Dwarven Noble",
            time: 25,
            res: 15,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Whispered Secrets-wise,Accounting,Soothing Platitudes,Sing",
            "Trait List": "Humility in the Face of Your Betters",
            leads: "Guilder,Artificer,Outcast",
            restrictions: "",
        },
        {
            name: "Axe Bearer",
            setting: "Dwarven Noble",
            time: 20,
            res: 25,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Throwing,Formation Fighting Training,Shield Training,Armor Training,Axe",
            "Trait List": "Proud",
            leads: "Host,Outcast",
            restrictions: "Noble Ardent or Banner Bearer",
        },
        {
            name: "Chronicler",
            setting: "Dwarven Noble",
            time: 50,
            res: 20,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Oath-wise,Symbology,Etiquette,Cartography,Poetry,Dwarf-wise,Clan-wise,Ancient History,Illuminations",
            "Trait List": "",
            leads: "Guilder,Artificer,Host",
            restrictions: "Abecedart; Khirurgeon; or Graybeard",
        },
        {
            name: "Seneschal",
            setting: "Dwarven Noble",
            time: 55,
            res: 50,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Hold-wise,Estate Management,Command,Etiquette",
            "Trait List": "Practical",
            leads: "Guilder,Host",
            restrictions: "Trader; Longbeard; Quartermaster; Chronicler; Khirurgeon; or Graybeard",
        },
        {
            name: "Treasurer",
            setting: "Dwarven Noble",
            time: 75,
            res: 100,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Administration,Treasure-wise,Accounting,Etiquette",
            "Trait List": "Rainman,Dangerous Obsession",
            leads: "Outcast,Host",
            restrictions: "Seneschal; Artificer; or Warden",
        },
        {
            name: "High Captain",
            setting: "Dwarven Noble",
            time: 75,
            res: 75,
            stats: "1P",
            "General Points": 2,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Conspicuous,Strategy,Command",
            "Trait List": "Muttering,Stentorious Voice",
            leads: "Outcast,Host",
            restrictions: "Noble Axe Bearer and either Captain or Warden",
        },
        {
            name: "Prince",
            setting: "Dwarven Noble",
            time: 100,
            res: 200,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 2,
            "Skill List": "Burden of the Crown-wise,Command,Oratory,Intimidation,Etiquette,Conspicuous",
            "Trait List": "Baleful Stare,Galvanizing Presence,Grumbling",
            leads: "Outcast,Host",
            restrictions: "Born Noble and Noble Axe Bearer",
        },
        {
            name: "Foot Soldier",
            setting: "Dwarven Host",
            time: 10,
            res: 6,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Cadence-wise,Shield Training,Armor Training,Hammer,Brawling,Foraging",
            "Trait List": "Salt of the Earth",
            leads: "Clansman,Outcast,Guilder",
            restrictions: "",
        },
        {
            name: "Arbalester",
            setting: "Dwarven Host",
            time: 12,
            res: 12,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Windage-wise,Artillery Hand,Fletcher,Mending,Crossbow",
            "Trait List": "Squinty",
            leads: "Clansman,Outcast,Guilder",
            restrictions: "",
        },
        {
            name: "Banner Bearer",
            setting: "Dwarven Host",
            time: 7,
            res: 10,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Intimidation,Banner-wise,Conspicuous",
            "Trait List": "Obsessive,Resigned to Death",
            leads: "Clansman,Outcast,Guilder",
            restrictions: "",
        },
        {
            name: "Horncaller",
            setting: "Dwarven Host",
            time: 7,
            res: 9,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Suicidal Bravery-wise,Cadence-wise,Conspicuous,Links",
            "Trait List": "",
            leads: "Clansman,Outcast,Guilder",
            restrictions: "",
        },
        {
            name: "Axe Bearer",
            setting: "Dwarven Host",
            time: 15,
            res: 15,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Throwing,Formation Fighting Training,Shield Training,Armor Training,Intimidation,Conspicuous,Axe,Foraging",
            "Trait List": "Swaggering",
            leads: "Guilder,Outcast,Noble",
            restrictions: "Noble Ardent; Graybeard; or Banner Bearer",
        },
        {
            name: "Graybeard",
            setting: "Dwarven Host",
            time: 20,
            res: 20,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Campaign-wise,Command,Field Dressing,Intimidation",
            "Trait List": "Oddly Likeable,Chuffing",
            leads: "Guilder,Outcast,Noble",
            restrictions: "Axe Bearer; Longbeard; or three Host lifepaths",
        },
        {
            name: "Khirurgeon",
            setting: "Dwarven Host",
            time: 25,
            res: 25,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Infection-wise,Cooking,Soothing Platitudes,Khirurgy",
            "Trait List": "",
            leads: "Guilder,Outcast,Noble",
            restrictions: "Abecedart; Seneschal; or Graybeard",
        },
        {
            name: "Quartermaster",
            setting: "Dwarven Host",
            time: 50,
            res: 35,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Host-wise,Supply-wise,Strategy,Accounting,Logistics",
            "Trait List": "No Nonsense",
            leads: "Guilder,Outcast,Noble",
            restrictions: "Seneschal; Treasurer. Trader; or Graybeard",
        },
        {
            name: "Captain",
            setting: "Dwarven Host",
            time: 55,
            res: 40,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Graybeard-wise,Cartography,Strategy,Formation Fighting Training,Conspicuous,Command",
            "Trait List": "",
            leads: "Guilder,Outcast,Noble",
            restrictions: "Prince or Graybeard",
        },
        {
            name: "Artillerist",
            setting: "Dwarven Host",
            time: 55,
            res: 45,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Structural Weakness-wise,Carpentry,Mending,Artillerist",
            "Trait List": "Complaining",
            leads: "Artificer,Outcast,Noble",
            restrictions: "Mask Bearer; Craftsman; Foreman; or three Arbalester lifepaths",
        },
        {
            name: "Engineer",
            setting: "Dwarven Host",
            time: 60,
            res: 50,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Leverage-wise,Scavenging,War Engineer,Jargon",
            "Trait List": "Estimation",
            leads: "Artificer,Noble",
            restrictions: "Artillerist or Mask Bearer",
        },
        {
            name: "Warden",
            setting: "Dwarven Host",
            time: 75,
            res: 65,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Champion-wise,Etiquette,Strategy,Observation,Oratory,Conspicuous",
            "Trait List": "Hard as Nails,Chuntering",
            leads: "Outcast,Noble",
            restrictions: "Prince; Captain; or High Captain",
        },
        {
            name: "Adventurer",
            setting: "Dwarven Outcast",
            time: 5,
            res: 10,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 12,
            "Trait Points": 2,
            "Skill List": "Lost Treasures-wise,Symbology,Obscure History,Appraisal,Lock Pick,Crossbow,Sword,Knives,Brawling,Firebuilding,Haggling,Herbalism,Knots,Climbing,Survival",
            "Trait List": "Boaster,Adventurer",
            leads: "Clansman,Guilder",
            restrictions: "",
        },
        {
            name: "Gambler",
            setting: "Dwarven Outcast",
            time: 7,
            res: 15,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Cheat-wise,Sleight of Hand,Observation,Games of Chance",
            "Trait List": "Stone-Faced",
            leads: "Clansman",
            restrictions: "",
        },
        {
            name: "Oathbreaker",
            setting: "Dwarven Outcast",
            time: 20,
            res: 5,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Oath-wise,Falsehood,Ugly Truth",
            "Trait List": "Bitter,Oathbreaker",
            leads: "Clansman",
            restrictions: "",
        },
        {
            name: "Drunk",
            setting: "Dwarven Outcast",
            time: 10,
            res: 5,
            stats: "",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Tavern Tales-wise,Drunking,Stentorious Singing",
            "Trait List": "Drunk,Despondent",
            leads: "Clansman",
            restrictions: "",
        },
        {
            name: "Coward",
            setting: "Dwarven Outcast",
            time: 15,
            res: 5,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 3,
            "Skill List": "Hypocritical Bastards-wise,Oratory,Ugly Truth,Inconspicuous",
            "Trait List": "Branded a Coward",
            leads: "Clansman,Guilder,Artificer,Dwarven Noble,Dwarven Outcast,Host",
            restrictions: "",
        },
        {
            name: "Rune Caster",
            setting: "Dwarven Outcast",
            time: 20,
            res: 6,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Bad End-wise,Scavenging,Foraging,Rune Casting",
            "Trait List": "Slave to Fate",
            leads: "Clansman,Guilder,Artificer,Dwarven Noble",
            restrictions: "",
        }
    ]