// TODO: format stats, skills and traits.

export default
    [
        {
            name: "Born Chattel",
            setting: "Chattel",
            time: 10,
            res: 5,
            stats: "1P",
            "General Points": 2,
            "Skill Points": 0,
            "Trait Points": 1,
            "Skill List": "",
            "Trait List": "",
            leads: "Black Legion,Servant",
            restrictions: "",
        },
        {
            name: "Cattle Slave",
            setting: "Chattel",
            time: 5,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Animal Husbandry",
            "Trait List": "Kicking the Beast,Shouting,Screaming,Tasting the Lash",
            leads: "",
            restrictions: "",
        },
        {
            name: "Scavenger",
            setting: "Chattel",
            time: 3,
            res: 6,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 2,
            "Skill List": "Inconspicuous,Foraging",
            "Trait List": "Scavenger,Stealing,Hiding,Running (Away),Tasting the Lash",
            leads: "Black Legion",
            restrictions: "",
        },
        {
            name: "Forge Slave",
            setting: "Chattel",
            time: 5,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Ditch Digging",
            "Trait List": "Numb,Back-Breaking Labor,Pain Life,Tasting the Lash",
            leads: "",
            restrictions: "",
        },
        {
            name: "Hauler",
            setting: "Chattel",
            time: 5,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Beast of Burden-wise,Driving",
            "Trait List": "Yowling,Spitting,Cursing,Back-Breaking Labor,Tasting the Lash",
            leads: "",
            restrictions: "",
        },
        {
            name: "Cutter Slave",
            setting: "Chattel",
            time: 5,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Ditch Digging,Tree Pulling",
            "Trait List": "Back-Breaking Labor,Hatred of Forests,Tasting the Lash",
            leads: "",
            restrictions: "",
        },
        {
            name: "Tunneler",
            setting: "Chattel",
            time: 4,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Tunnel-wise,Ditch Digging",
            "Trait List": "Black Lung,Back-Breaking Labor,Tasting the Lash",
            leads: "",
            restrictions: "",
        },
        {
            name: "Ravager",
            setting: "Chattel",
            time: 3,
            res: 8,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Intimidation,Cudgel,Brawling",
            "Trait List": "Pack Hunter",
            leads: "Black Legion",
            restrictions: "",
        },
        {
            name: "Woodcutter",
            setting: "Chattel",
            time: 7,
            res: 9,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Intimidation,Mending,Rude Carpentry",
            "Trait List": "",
            leads: "",
            restrictions: "Cutter Slave",
        },
        {
            name: "Butcher",
            setting: "Chattel",
            time: 7,
            res: 9,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Intimidation,Tanner,Butchery",
            "Trait List": "",
            leads: "",
            restrictions: "Cattle Slave",
        },
        {
            name: "Forger",
            setting: "Chattel",
            time: 7,
            res: 9,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Intimidation,Blacksmith",
            "Trait List": "Singed",
            leads: "",
            restrictions: "Forge Slave",
        },
        {
            name: "Pitwright",
            setting: "Chattel",
            time: 8,
            res: 10,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Intimidation,Mining",
            "Trait List": "Deep Sense",
            leads: "",
            restrictions: "Tunneler",
        },
        {
            name: "Edge Grinder",
            setting: "Chattel",
            time: 10,
            res: 15,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Tanner,Armorer,Weaponsmith,Mending",
            "Trait List": "Suspicious",
            leads: "Black Legion",
            restrictions: "Forger",
        },
        {
            name: "Whipmaster",
            setting: "Chattel",
            time: 9,
            res: 15,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Torture,Brawling,Intimidation,Interrogation",
            "Trait List": "Where There's a Whip, There's a Way",
            leads: "Black Legion",
            restrictions: "Pitwright, Forger, four slave lifepaths, or any Great and Black or Legion lifepath",
        },
        {
            name: "Born Great",
            setting: "Great and Black",
            time: 10,
            res: 5,
            stats: "",
            "General Points": 3,
            "Skill Points": 0,
            "Trait Points": 2,
            "Skill List": "",
            "Trait List": "Enemy of the Sun,Born to Rule Them All",
            leads: "Servant of the Dark",
            restrictions: "",
        },
        {
            name: "The Rites",
            setting: "Great and Black",
            time: 3,
            res: 3,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Torture,Intimidation,Brawling",
            "Trait List": "Sprinter,Life is Death",
            leads: "Legion,Servant of the Dark",
            restrictions: "May only be taken once; must be 2nd lifepath",
        },
        {
            name: "Servant of the Gate",
            setting: "Great and Black",
            time: 4,
            res: 7,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 1,
            "Skill List": "Hauling,Ditch Digging,Soothing Platitudes",
            "Trait List": "Back-Breaking Labor,Humble Before My Master",
            leads: "Legion,Chattel",
            restrictions: "",
        },
        {
            name: "Follower",
            setting: "Great and Black",
            time: 5,
            res: 9,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Clan-wise,Shield Training,Riding,Mace,Knives,Bow,Axe,Armor Training",
            "Trait List": "Silent Hatred",
            leads: "Legion,Chattel",
            restrictions: "The Rites or Astride the Beast",
        },
        {
            name: "Black Destroyer",
            setting: "Great and Black",
            time: 6,
            res: 12,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 2,
            "Skill List": "Spear,Axe,Riding,Great Wolf Husbandry,Mounted Combat Training",
            "Trait List": "Low Cunning,Intense Hatred",
            leads: "Chattel",
            restrictions: "Follower, Astride the Beast, or Headtaker",
        },
        {
            name: "Named",
            setting: "Great and Black",
            time: 8,
            res: 25,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Torture,Brutal Intimidation,Command",
            "Trait List": "Savage Consequences",
            leads: "Chattel",
            restrictions: "Black Destroyer, Troll Lord, or Head Taker",
        },
        {
            name: "Siege Master",
            setting: "Great and Black",
            time: 10,
            res: 30,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mending,Artillerist,Siege Engineer",
            "Trait List": "Brutish Efficiency,The Bigger They Come...",
            leads: "Chattel",
            restrictions: "Servant of the Gate",
        },
        {
            name: "Gate Forger",
            setting: "Great and Black",
            time: 10,
            res: 30,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mining,Bastions of Hatred,Mason",
            "Trait List": "Rare Talent",
            leads: "Chattel",
            restrictions: "Siege Master",
        },
        {
            name: "Whisperer",
            setting: "Great and Black",
            time: 9,
            res: 40,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Ambition-wise,Clan-wise,Persuasion,Falsehood,Poisonous Platitudes",
            "Trait List": "Poisonous Ambition,Forked Tongue",
            leads: "Servant of the Dark",
            restrictions: "Slave to the Dark, Whipmaster; Gate Forger, or Bears the Lash",
        },
        {
            name: "Great One",
            setting: "Great and Black",
            time: 20,
            res: 60,
            stats: "2M;P",
            "General Points": 1,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Name Ritual,Strategy,Command",
            "Trait List": "Unrelenting Hatred,Flights of Murderous Fancy,Brooding",
            leads: "",
            restrictions: "Named and the Born to Rule Them All Trait",
        },
        {
            name: "Goblin",
            setting: "Black Legion",
            time: 3,
            res: 2,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Brawling,Foraging",
            "Trait List": "Marching,Charging Blindly,Running (Away),Exhausted,Tasting the Lash",
            leads: "Chattel",
            restrictions: "May not be Born Great",
        },
        {
            name: "Sun Blotter",
            setting: "Black Legion",
            time: 3,
            res: 3,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 1,
            "Skill List": "Fletcher,Mending,Bow",
            "Trait List": "Running (Away),Hiding",
            leads: "Chattel",
            restrictions: "May not be Born Great",
        },
        {
            name: "Nightseeker",
            setting: "Black Legion",
            time: 4,
            res: 4,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Garrote,Climbing,Stealthy,Trapper,Tracking,Orienteering",
            "Trait List": "Tasting the Lash",
            leads: "Chattel",
            restrictions: "May not be Born Great; Legioner, Sun Blotter, Scavenger, or Ravager",
        },
        {
            name: "Legioner",
            setting: "Black Legion",
            time: 4,
            res: 5,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Foraging,Brawling,Shield Training,Spear",
            "Trait List": "",
            leads: "Chattel",
            restrictions: "Ravager, Whipmaster, or Goblin; may not be born great",
        },
        {
            name: "Hatred Bearer",
            setting: "Black Legion",
            time: 1,
            res: 15,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 1,
            "Skill List": "Black Legion-wise,Conspicuous",
            "Trait List": "Booming Voice,Paranoid,Psychotic",
            leads: "Chattel",
            restrictions: "The Rites, Legioner, or Whipmaster",
        },
        {
            name: "Despair Shouter",
            setting: "Black Legion",
            time: 3,
            res: 10,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 2,
            "Skill List": "Brawling,Intimidation,Brazen Horn of Despair",
            "Trait List": "Reviled",
            leads: "Chattel",
            restrictions: "The Rites, Legioner, or Whipmaster",
        },
        {
            name: "Black Hunter",
            setting: "Black Legion",
            time: 5,
            res: 5,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Stealthy,Field Dressing,Hunting,Bow",
            "Trait List": "Black Bile Poison",
            leads: "Chattel",
            restrictions: "Follower, Ravager, or Nightseeker",
        },
        {
            name: "Astride the Beast",
            setting: "Black Legion",
            time: 5,
            res: 6,
            stats: "1P",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Armor Training,Spear,Intimidation,Great Wolf Husbandry,Riding,Mounted Combat Training",
            "Trait List": "Cry of Doom,Brash",
            leads: "Chattel,Great and Black",
            restrictions: "Black Hunter or Follower",
        },
        {
            name: "Bears the Lash",
            setting: "Black Legion",
            time: 6,
            res: 9,
            stats: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Brawling,Sword,Command,Torture,Intimidation,Whip-wise",
            "Trait List": "Where There's a Whip, There's a Way",
            leads: "Chattel,Great and Black",
            restrictions: "Whipmaster, Black Hunter, Astride the Beast, or the Rites",
        },
        {
            name: "Packmaster",
            setting: "Black Legion",
            time: 7,
            res: 10,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mending,Pack-wise,Great Wolf-wise,Great Wolf Husbandry",
            "Trait List": "Show No Fear,\"Where There's a Whip, There's a Way\",Flea-Bitten",
            leads: "Chattel,Great and Black",
            restrictions: "Bears the Lash, Follower, Whipmaster, Master of Eight, or Knower of Secrets",
        },
        {
            name: "Head Taker",
            setting: "Black Legion",
            time: 6,
            res: 15,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Brawling,Axe,Brutal Intimidation,Command",
            "Trait List": "Taste for Man-Flesh,Fondness for Elven Blood,Unrelenting Savagery",
            leads: "Chattel,Great and Black",
            restrictions: "Bears the Lash, Black Destroyer, or Named",
        },
        {
            name: "Troll Lord",
            setting: "Black Legion",
            time: 5,
            res: 20,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Shield Training,Hammer,Troll Etiquette,Troll-wise",
            "Trait List": "Troll Speak,Arrogant",
            leads: "Great and Black,Servant of the Dark Blood",
            restrictions: "Bears the Lash, Packmaster, or Named",
        },
        {
            name: "Slave to the Dark",
            setting: "Servant of the Dark Blood",
            time: 6,
            res: 3,
            stats: "",
            "General Points": 0,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Servant-wise",
            "Trait List": "Naked Hatred,Fearful Respect of the Servants",
            leads: "Chattel",
            restrictions: "",
        },
        {
            name: "Drinker of the Dark",
            setting: "Servant of the Dark Blood",
            time: 5,
            res: 6,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 3,
            "Skill List": "Doctrine of Night's Blood",
            "Trait List": "Void Embrace,Blasphemer,Stark Madness",
            leads: "Chattel",
            restrictions: "Slave to the Dark",
        },
        {
            name: "Bloodletter",
            setting: "Servant of the Dark Blood",
            time: 5,
            res: 6,
            stats: "1M;P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Knives,Intimidation,Torture,Rituals of Blood",
            "Trait List": "",
            leads: "Chattel",
            restrictions: "Drinker of the Dark",
        },
        {
            name: "Knower of Secrets",
            setting: "Servant of the Dark Blood",
            time: 6,
            res: 7,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Foraging,Vile Poisoner,Rituals of Night",
            "Trait List": "",
            leads: "Chattel,Legion",
            restrictions: "Drinker of the Dark",
        },
        {
            name: "Master of Eight",
            setting: "Servant of the Dark Blood",
            time: 8,
            res: 8,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 2,
            "Skill List": "Climbing,Web-wise,Mounted Combat Training,Riding,Spider Husbandry",
            "Trait List": "Affinity for Spiders,Batshit",
            leads: "Chattel,Legion",
            restrictions: "Knower of Secrets",
        },
        {
            name: "Master of Blood",
            setting: "Servant of the Dark Blood",
            time: 7,
            res: 8,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Wolf-wise,Elf-wise,Orc-wise,Animal Husbandry,Rituals-wise",
            "Trait List": "Where There's a Whip, There's a Way",
            leads: "",
            restrictions: "Bloodletter",
        },
        {
            name: "Master of Darkness",
            setting: "Servant of the Dark Blood",
            time: 7,
            res: 8,
            stats: "1M/P",
            "General Points": 0,
            "Skill Points": 3,
            "Trait Points": 1,
            "Skill List": "Tunnel-wise,Cave-wise",
            "Trait List": "",
            leads: "",
            restrictions: "Knower of Secrets",
        },
        {
            name: "Dark Summoner",
            setting: "Servant of the Dark Blood",
            time: 10,
            res: 12,
            stats: "1M/P",
            "General Points": 1,
            "Skill Points": 3,
            "Trait Points": 1,
            "Skill List": "Darkness-wise",
            "Trait List": "",
            leads: "",
            restrictions: "Master of Darkness",
        },
        {
            name: "Blood Summoner",
            setting: "Servant of the Dark Blood",
            time: 10,
            res: 12,
            stats: "1M/P",
            "General Points": 1,
            "Skill Points": 3,
            "Trait Points": 1,
            "Skill List": "Troll-wise,Bat-wise,Poison-wise",
            "Trait List": "",
            leads: "",
            restrictions: "Master of Blood",
        },
        {
            name: "Servant",
            setting: "Servant of the Dark Blood",
            time: 50,
            res: 30,
            stats: "1M",
            "General Points": 2,
            "Skill Points": 2,
            "Trait Points": 1,
            "Skill List": "Name Ritual,Great and Black-wise",
            "Trait List": "",
            leads: "",
            restrictions: "Dark Summoner or Blood Summoner; Born to Rule Them All Trait",
        },
        {
            name: "Master of the Weak",
            setting: "Servant of the Dark Blood",
            time: 7,
            res: 8,
            stats: "M/P",
            "General Points": "",
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Murder-wise,Graveyard-wise,Apocalypse-wise,Death Art",
            "Trait List": "Feared",
            leads: "",
            restrictions: "Knower of Secrets",
        }
    ]