// TODO: format stats, skills and traits.

export default
    [
        {
            name: "Born Wilder Elf",
            isBornLifepath: true,
            setting: "Wilderlands",
            time: 20,
            res: 5,
            stat: "",
            "General Points": 4,
            "Skill Points": 2,
            "Trait Points": 1,
            "Skill List": "Elven Script,Sing",
            "Trait List": "",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Rider",
            setting: "Wilderlands",
            time: 20,
            res: 8,
            stat: "1P",
            "General Points": "",
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Lay of the Horse,The Gift of Speed,Riding",
            "Trait List": "Oikofugic",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Harvester",
            setting: "Wilderlands",
            time: 50,
            res: 5,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mending,Animal Husbandry,Firebuilding,Farming,Round of Harvest",
            "Trait List": "Seasoned",
            leads: "Protector",
            restrictions: "",
        },
        {
            name: "Gatherer",
            setting: "Wilderlands",
            time: 40,
            res: 3,
            stat: "",
            "General Points": "",
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Orienteering,Herb-wise,Rhyme of the Gatherer",
            "Trait List": "Rough Hands",
            leads: "",
            restrictions: "",
        },
        {
            name: "Fisherman",
            setting: "Wilderlands",
            time: 50,
            res: 8,
            stat: "",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Rigging,Seamanship,Cooking,Mending,Knots,Boatwright,Pilot,Hymn of Scales and Fins",
            "Trait List": "Wary",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Shepherd",
            setting: "Wilderlands",
            time: 45,
            res: 6,
            stat: "",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 1,
            "Skill List": "Wolf-wise,Climbing,Song of Flocks and Herds",
            "Trait List": "Never Cry Wolf",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Wanderer",
            setting: "Wilderlands",
            time: 75,
            res: 5,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Any wise,Foraging,Air of Gates,Song of Paths and Ways",
            "Trait List": "",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Huntsman",
            setting: "Wilderlands",
            time: 45,
            res: 9,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Observation,Stealthy,Tracking,Bow,Javelin,Call of the Wild",
            "Trait List": "Watchful",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Chandler",
            setting: "Wilderlands",
            time: 50,
            res: 15,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Appraisal,Conspicuous,Haggling,Chant of Offering",
            "Trait List": "",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Weaver",
            setting: "Wilderlands",
            time: 50,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Mending,Threading Chant,Weaving Way",
            "Trait List": "Fateful",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Forester",
            setting: "Wilderlands",
            time: 90,
            res: 5,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Song of the Eldar,Tree-wise,Forest-wise,Song of Arbors",
            "Trait List": "Stern",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Vintner",
            setting: "Wilderlands",
            time: 60,
            res: 20,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Terroir-wise,Vintage-wise,Cooper,Vine-wise,Purple Song",
            "Trait List": "Rarified",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Miller",
            setting: "Wilderlands",
            time: 60,
            res: 18,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Grain-wise,Mill-wise,Carpentry,Mending,Grain Song",
            "Trait List": "Earthen",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Song Singer",
            setting: "Wilderlands",
            time: 45,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Oratory,Lament of the Westering Sun,Song of Soothing,Song of Songs",
            "Trait List": "Vocal",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Spouse",
            setting: "Wilderlands",
            time: 75,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Fealty-wise,Song of Feasting,Rhyme of Rules,Song of Soothing",
            "Trait List": "",
            leads: "Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Patriarch/Matriarch",
            setting: "Wilderlands",
            time: 100,
            res: 15,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Dignity of the Wilderlands,Lyric of Healing,Homesong",
            "Trait List": "Patriarchal/Matriarchal",
            leads: "Citadel",
            restrictions: "",
        },
        {
            name: "Elder",
            setting: "Wilderlands",
            time: 150,
            res: 30,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Council-Caller,Verse of Decision",
            "Trait List": "Wise Aphorisms",
            leads: "Citadel,Etharch",
            restrictions: "",
        },
        {
            name: "Citadel Born",
            isBornLifepath: true,
            setting: "Citadel",
            time: 20,
            res: 7,
            stat: "",
            "General Points": 5,
            "Skill Points": 2,
            "Trait Points": 1,
            "Skill List": "Sing,Elven Script",
            "Trait List": "",
            leads: "Wilderlands",
            restrictions: "",
        },
        {
            name: "Servitor",
            setting: "Citadel",
            time: 20,
            res: 5,
            stat: "",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Althing-wise,Citadel-wise,Observation,Hauling",
            "Trait List": "Lifting Heavy Things,Humility",
            leads: "Wilderlands,Protector",
            restrictions: "",
        },
        {
            name: "Wanderer",
            setting: "Citadel",
            time: 75,
            res: 5,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Streetwise,Scavenging,Air of Gates,Song of Paths and Ways",
            "Trait List": "Lonesome",
            leads: "Wilderlands",
            restrictions: "",
        },
        {
            name: "Song Singer",
            setting: "Citadel",
            time: 25,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Lament of the Stars,Song of Soothing,Song of Songs,Sing",
            "Trait List": "Voice in the Crowd",
            leads: "Wilderlands,Protector",
            restrictions: "",
        },
        {
            name: "Student",
            setting: "Citadel",
            time: 20,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Oratory,Etiquette,Elven Script,Ballad of History,Lyric of Law",
            "Trait List": "Educated",
            leads: "Wilderlands,Protector",
            restrictions: "",
        },
        {
            name: "Clothier",
            setting: "Citadel",
            time: 75,
            res: 20,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Weaving Way,Leathercraft,Embroidery,Threading Chant",
            "Trait List": "Well Dressed",
            leads: "Wilderlands,Protector",
            restrictions: "",
        },
        {
            name: "Soldier-Protector",
            setting: "Citadel",
            time: 5,
            res: 10,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Mending,Fletcher,Knives,Bow,Sword,Shield Training,Armor Training,Alarm",
            "Trait List": "Dutiful",
            leads: "Wilderlands,Protector,Etharch",
            restrictions: "Wanderer; Seafarer; Spouse; Rider; Huntsman; any Etharch or Protector lifepath",
        },
        {
            name: "Seafarer",
            setting: "Citadel",
            time: 50,
            res: 5,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Spear,Pilot,Seamanship,Rhyme of the Mariner,Rope Chant,Weathersong",
            "Trait List": "Rower,Call of the Sea",
            leads: "Wilderlands,Protector",
            restrictions: "",
        },
        {
            name: "Sea Captain",
            setting: "Citadel",
            time: 100,
            res: 15,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Sword,Oratory,Command,Supplication to the Wind,Slip of the Currents",
            "Trait List": "",
            leads: "Wilderlands,Protector,Etharch",
            restrictions: "Seafarer; Adjutant; Lieutenant; or Sword Singer",
        },
        {
            name: "Novice",
            setting: "Citadel",
            time: 10,
            res: 10,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Elven Artifact-wise,Craft-wise,Mending",
            "Trait List": "Loyal",
            leads: "Wilderlands",
            restrictions: "",
        },
        {
            name: "Shaper",
            setting: "Citadel",
            time: 35,
            res: 15,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Smithcraft,Stonecraft,Woodcraft",
            "Trait List": "Long Fingered",
            leads: "Wilderlands,Protector",
            restrictions: "Novice",
        },
        {
            name: "Jeweler",
            setting: "Citadel",
            time: 75,
            res: 20,
            stat: "",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Appraisal,Gemcraft,Jewelcraft",
            "Trait List": "Nimble,Patient",
            leads: "Wilderlands,Protector",
            restrictions: "Shaper",
        },
        {
            name: "Artisan",
            setting: "Citadel",
            time: 150,
            res: 40,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Antiphon Union Training,Canticle of Years,Starcraft,Archcraft",
            "Trait List": "",
            leads: "Wilderlands,Protector,Etharch",
            restrictions: "Shaper",
        },
        {
            name: "Keel Master",
            setting: "Citadel",
            time: 100,
            res: 25,
            stat: "1M/P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 2,
            "Skill List": "Carving,Ship-wise,Shipwright",
            "Trait List": "Perfectionist",
            leads: "Wilderlands,Protector",
            restrictions: "Shaper",
        },
        {
            name: "Artist",
            setting: "Citadel",
            time: 60,
            res: 12,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 2,
            "Skill List": "Painting,Song of Form",
            "Trait List": "Appreciation for Beauty",
            leads: "Wilderlands",
            restrictions: "",
        },
        {
            name: "Bard",
            setting: "Citadel",
            time: 65,
            res: 20,
            stat: "1M/P",
            "General Points": 0,
            "Skill Points": 11,
            "Trait Points": 1,
            "Skill List": "Flute,Lyre,Conspicuous,Oratory,Tract of Enmity,Verse of Friendship,Lament of Mourning,Song of Merriment",
            "Trait List": "",
            leads: "Wilderlands,Protector",
            restrictions: "Song Singer",
        },
        {
            name: "Adjutant",
            setting: "Citadel",
            time: 75,
            res: 20,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 2,
            "Skill List": "Protector-wise,Citadel-wise,Etharch-wise,Administration,Etiquette,Code of Citadels",
            "Trait List": "Patient,Organized",
            leads: "Wilderlands,Protector",
            restrictions: "Herald; Attendant; Student; or Spouse",
        },
        {
            name: "Loremaster",
            setting: "Citadel",
            time: 200,
            res: 25,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Rhyme of Tongues,Canticle of Years,Lyric of Law,Ballad of History,Research,Ancient and Obscure History",
            "Trait List": "",
            leads: "Wilderlands,Etharch",
            restrictions: "Bard; Adjutant; Steward; or Patriarch/Matriarch",
        },
        {
            name: "Althing",
            setting: "Citadel",
            time: 250,
            res: 100,
            stat: "1M;P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 2,
            "Skill List": "Administration,Ugly Truth,Soothing Platitudes,Persuasion,Song of Silence,Council-Caller",
            "Trait List": "Servant of the Citadel",
            leads: "Wilderlands,Protector,Etharch",
            restrictions: "Patriarch/Matriarch; Loremaster; Steward; Bard; Artisan; Sea Captain; or Captain",
        },
        {
            name: "Born Etharch",
            isBornLifepath: true,
            setting: "Etharch",
            time: 25,
            res: 10,
            stat: "",
            "General Points": 5,
            "Skill Points": 2,
            "Trait Points": 2,
            "Skill List": "Sing,Etiquette,Elven Script",
            "Trait List": "Aman,Fea,Etharchal",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Student",
            setting: "Etharch",
            time: 25,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Song of the Eldar,Calligraphy,Oratory,Ballad of History,Lyric of Law,Ages of the Etharch",
            "Trait List": "Learned",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Attendant",
            setting: "Etharch",
            time: 25,
            res: 15,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 4,
            "Trait Points": 2,
            "Skill List": "Sword,Brawling,Riding,Etiquette",
            "Trait List": "Calm Demeanor",
            leads: "Wilderlands,Citadel,Protector",
            restrictions: "",
        },
        {
            name: "Second",
            setting: "Etharch",
            time: 35,
            res: 15,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 2,
            "Skill List": "Mounted Combat Training,Riding,Mending,Bow,Knives,Sword,Song of Bonding",
            "Trait List": "Patient,Lesson of One",
            leads: "Citadel,Wilderlands,Etharch,Protector",
            restrictions: "Attendant; Bowyer; Spearbearer; Seafarer; or Soldier-Protector",
        },
        {
            name: "Sword Singer",
            setting: "Etharch",
            time: 40,
            res: 10,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Brawling,Knives,Shield Training,Armor Training,Sword,Song of the Sword",
            "Trait List": "Cool Headed,Fealty to the Fea",
            leads: "Protector,Citadel,Etharch,Wilderlands",
            restrictions: "Second; Lancer; or Lieutenant",
        },
        {
            name: "Steward",
            setting: "Etharch",
            time: 110,
            res: 20,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Intrigue-wise,Estate-wise,Etiquette,Accounting,Estate Management",
            "Trait List": "",
            leads: "Citadel,Protector",
            restrictions: "Lieutenant; Artisan; Bard; Loremaster; Adjutant; Sea Captain; or Matriarch/Patriarch",
        },
        {
            name: "Prince/Princess",
            setting: "Etharch",
            time: 150,
            res: 100,
            stat: "1M/P",
            "General Points": 4,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Voice of Ages,Song of Lordship",
            "Trait List": "Prince/Princess of the Blood",
            leads: "Citadel,Protector",
            restrictions: "Fea trait and Sword Singer",
        },
        {
            name: "Etharch",
            setting: "Etharch",
            time: 250,
            res: 200,
            stat: "1M;P",
            "General Points": 4,
            "Skill Points": 8,
            "Trait Points": 2,
            "Skill List": "Discener,Doom Sayer,Voice of Thunder,Council-Caller",
            "Trait List": "Lord of Ages",
            leads: "Citadel,Protector",
            restrictions: "Aman trait and either Loremaster or Prince/Princess",
        },
        {
            name: "Rider",
            setting: "Protector",
            time: 15,
            res: 8,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Lay of the Horse,The Gift of Speed,Animal Husbandry,Riding",
            "Trait List": "Smells like a Horse",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Herald",
            setting: "Protector",
            time: 35,
            res: 10,
            stat: "1M/P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 2,
            "Skill List": "Silver Trumpet,Recitation of Ages,Evensong,Mornsong,Paean of Deeds",
            "Trait List": "Stoic",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Soother",
            setting: "Protector",
            time: 30,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 6,
            "Trait Points": 1,
            "Skill List": "Foraging,Doom of Strength,Song of Soothing,Lyric of Healing",
            "Trait List": "",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Ranger",
            setting: "Protector",
            time: 45,
            res: 10,
            stat: "1M/P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Lyric of Healing,Threne of the Chameleon,Song of Soothing,Rhyme of the Pathfinder ,Foraging,Bow,Stealthy,Observation",
            "Trait List": "Sprinter,Grey Mantel",
            leads: "Wilderlands",
            restrictions: "",
        },
        {
            name: "Bowyer",
            setting: "Protector",
            time: 20,
            res: 8,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Bow-wise,Bow,Mending,Bowcraft",
            "Trait List": "Circumspect",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Spearbearer",
            setting: "Protector",
            time: 20,
            res: 8,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 8,
            "Trait Points": 1,
            "Skill List": "Formation Fighting Training,Armor Training,Spear,Spearcraft",
            "Trait List": "",
            leads: "Wilderlands,Citadel",
            restrictions: "",
        },
        {
            name: "Sword Singer",
            setting: "Protector",
            time: 30,
            res: 10,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Song of the Sword,Brawling,Knives,Shield Training,Armor Training,Sword",
            "Trait List": "Sword of the White Towers",
            leads: "Wilderlands,Citadel,Etharch,Protector",
            restrictions: "Second; Soldier-Protector; Soother; Spouse; or Spearbearer",
        },
        {
            name: "Outrider",
            setting: "Protector",
            time: 20,
            res: 10,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 1,
            "Skill List": "Stealthy,Mending,Animal Husbandry,Mounted Combat: Bowman Training,Trails-wise,Observation,Spear,Bow",
            "Trait List": "Daring",
            leads: "Wilderlands,Citadel",
            restrictions: "Rider",
        },
        {
            name: "Lancer",
            setting: "Protector",
            time: 50,
            res: 12,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Armor Training,Shield Training,Mounted Combat Training,Lance,Lament for the Fallen,Song of Burning Bright",
            "Trait List": "",
            leads: "Wilderlands,Citadel,Etharch,Protector",
            restrictions: "Outrider or Second",
        },
        {
            name: "Lieutenant",
            setting: "Protector",
            time: 65,
            res: 10,
            stat: "1M",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Formation Fighting Training,Shield Training,Sword,Command,Paean of Deeds",
            "Trait List": "Ear to the Ground",
            leads: "Wilderlands,Citadel,Protector,Etharch",
            restrictions: "Sword Singer; Lancer; Sea Captain; or two Bowyer/Spearbearer lifepaths",
        },
        {
            name: "Captain",
            setting: "Protector",
            time: 85,
            res: 15,
            stat: "1M;P",
            "General Points": 0,
            "Skill Points": 9,
            "Trait Points": 2,
            "Skill List": "The Hymn of Victory,Silent Fury,Monody of the March,Formation Fighting Training,Tactics,Command,Sword,Oratory",
            "Trait List": "Sworn to the Lord Protector",
            leads: "Wilderlands,Citadel,Protector,Etharch",
            restrictions: "Lieutenant; Prince; Sea Captain; Steward; or two Sword Singer lps",
        },
        {
            name: "Armorer",
            setting: "Protector",
            time: 90,
            res: 15,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 7,
            "Trait Points": 1,
            "Skill List": "Antiphon Union Training,Tanner,Sewing,Etching,Armorer",
            "Trait List": "Patient",
            leads: "Wilderlands,Citadel",
            restrictions: "Shaper or Bladesmith",
        },
        {
            name: "Bladesmith",
            setting: "Protector",
            time: 80,
            res: 15,
            stat: "1P",
            "General Points": 0,
            "Skill Points": 5,
            "Trait Points": 1,
            "Skill List": "Elven Blade-wise,Etching,Riddle of Steel",
            "Trait List": "Acute",
            leads: "Wilderlands,Citadel",
            restrictions: "Armorer; Shaper; Bowyer; or Spearbearer",
        },
        {
            name: "Lord Protector",
            setting: "Protector",
            time: 125,
            res: 60,
            stat: "1M;P",
            "General Points": 0,
            "Skill Points": 10,
            "Trait Points": 1,
            "Skill List": "Strategy,Logistics,Administration,Formation Fighting Training,Command,Ballad of Rage,Anthem of Courage,Strain of Far Sight",
            "Trait List": "Sworn to Protect",
            leads: "Wilderlands,Citadel,Protector,Etharch",
            restrictions: "Captain or Prince",
        }
    ]